version: '3.0'

services:
  neo4j:
    image: neo4j:4.2
    environment:
    - "NEO4J_AUTH=neo4j/secret"
    - "NEO4JLABS_PLUGINS=[\"apoc\"]"
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - ./var/neo4j/data:/data
    - ./var/neo4j/logs:/logs
  php:
    build:
      context: ./docker/php
    volumes:
    - ./app:/opt/app
    - ./docker/php/zz-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
